# Generated by Django 5.2.1 on 2025-09-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('authentication', '0004_rename_phone_user_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address'),
        ),
        migrations.RemoveField(
            model_name='citymunicipality',
            name='province',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('staff', 'Staff'), ('patient', 'Patient')], default='patient', help_text='User role in the system', max_length=10),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='CityMunicipality',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
